# Generated by Django 4.2 on 2024-09-30 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_category_todo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='todo',
            name='remind_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='reminder_time',
            field=models.DurationField(blank=True, help_text='Time before the due date when the reminder should be sent (e.g., 1 day or 1 hour).', null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
