# Generated by Django 5.1.1 on 2024-09-25 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_team_todo_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='team',
        ),
    ]
