# Generated by Django 5.1.1 on 2024-09-29 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_todo_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.team'),
        ),
    ]
