# Generated by Django 5.1.1 on 2024-09-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_todo_category_todo_due_date_todo_remind_sent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='remind_sent',
            new_name='reminder_sent',
        ),
    ]
