# Generated by Django 4.2 on 2024-09-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_rename_remind_sent_todo_reminder_sent'),
    ]

    operations = [
    ]
