# Generated by Django 4.2 on 2024-09-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20240930_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Errands', 'Errands'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
