# Generated by Django 4.2 on 2024-10-01 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_todo_team'),
        ('todo', '0010_todo_archived'),
    ]

    operations = [
    ]
